const rawCalendar = [
  {
    matchday: 1,
    date: "2026-08-23",
    matches: [
      ["Atalanta", "Sassuolo"],
      ["Bologna", "Lazio"],
      ["Frosinone", "Juventus"],
      ["Genoa", "Napoli"],
      ["Inter", "Monza"],
      ["Parma", "Cagliari"],
      ["Roma", "Fiorentina"],
      ["Torino", "Milan"],
      ["Udinese", "Como"],
      ["Venezia", "Lecce"],
    ],
  },
  {
    matchday: 2,
    date: "2026-08-30",
    matches: [
      ["Atalanta", "Bologna"],
      ["Cagliari", "Inter"],
      ["Fiorentina", "Frosinone"],
      ["Juventus", "Parma"],
      ["Lazio", "Genoa"],
      ["Lecce", "Roma"],
      ["Milan", "Venezia"],
      ["Monza", "Udinese"],
      ["Napoli", "Como"],
      ["Sassuolo", "Torino"],
    ],
  },
  {
    matchday: 3,
    date: "2026-09-06",
    matches: [
      ["Bologna", "Sassuolo"],
      ["Cagliari", "Lecce"],
      ["Fiorentina", "Torino"],
      ["Frosinone", "Venezia"],
      ["Genoa", "Como"],
      ["Inter", "Napoli"],
      ["Juventus", "Milan"],
      ["Parma", "Monza"],
      ["Roma", "Atalanta"],
      ["Udinese", "Lazio"],
    ],
  },
  {
    matchday: 4,
    date: "2026-09-13",
    matches: [
      ["Atalanta", "Cagliari"],
      ["Como", "Parma"],
      ["Genoa", "Frosinone"],
      ["Inter", "Udinese"],
      ["Lazio", "Milan"],
      ["Lecce", "Monza"],
      ["Napoli", "Bologna"],
      ["Sassuolo", "Juventus"],
      ["Torino", "Roma"],
      ["Venezia", "Fiorentina"],
    ],
  },
  {
    matchday: 5,
    date: "2026-09-20",
    matches: [
      ["Bologna", "Torino"],
      ["Fiorentina", "Napoli"],
      ["Frosinone", "Como"],
      ["Juventus", "Atalanta"],
      ["Milan", "Lecce"],
      ["Monza", "Sassuolo"],
      ["Parma", "Genoa"],
      ["Roma", "Inter"],
      ["Udinese", "Cagliari"],
      ["Venezia", "Lazio"],
    ],
  },
  {
    matchday: 6,
    date: "2026-10-11",
    matches: [
      ["Atalanta", "Venezia"],
      ["Cagliari", "Juventus"],
      ["Como", "Roma"],
      ["Genoa", "Fiorentina"],
      ["Inter", "Parma"],
      ["Lazio", "Monza"],
      ["Lecce", "Bologna"],
      ["Napoli", "Frosinone"],
      ["Sassuolo", "Milan"],
      ["Torino", "Udinese"],
    ],
  },
  {
    matchday: 7,
    date: "2026-10-18",
    matches: [
      ["Bologna", "Inter"],
      ["Fiorentina", "Como"],
      ["Frosinone", "Sassuolo"],
      ["Juventus", "Lazio"],
      ["Milan", "Atalanta"],
      ["Monza", "Cagliari"],
      ["Parma", "Torino"],
      ["Roma", "Genoa"],
      ["Udinese", "Lecce"],
      ["Venezia", "Napoli"],
    ],
  },
  {
    matchday: 8,
    date: "2026-10-25",
    matches: [
      ["Atalanta", "Frosinone"],
      ["Cagliari", "Bologna"],
      ["Como", "Sassuolo"],
      ["Genoa", "Venezia"],
      ["Inter", "Fiorentina"],
      ["Lazio", "Parma"],
      ["Lecce", "Juventus"],
      ["Napoli", "Roma"],
      ["Torino", "Monza"],
      ["Udinese", "Milan"],
    ],
  },
  {
    matchday: 9,
    date: "2026-10-28",
    matches: [
      ["Fiorentina", "Atalanta"],
      ["Frosinone", "Lecce"],
      ["Genoa", "Juventus"],
      ["Milan", "Bologna"],
      ["Monza", "Napoli"],
      ["Parma", "Udinese"],
      ["Roma", "Cagliari"],
      ["Sassuolo", "Lazio"],
      ["Torino", "Como"],
      ["Venezia", "Inter"],
    ],
  },
  {
    matchday: 10,
    date: "2026-11-01",
    matches: [
      ["Atalanta", "Parma"],
      ["Bologna", "Monza"],
      ["Como", "Venezia"],
      ["Frosinone", "Torino"],
      ["Juventus", "Napoli"],
      ["Lazio", "Cagliari"],
      ["Lecce", "Genoa"],
      ["Milan", "Inter"],
      ["Sassuolo", "Fiorentina"],
      ["Udinese", "Roma"],
    ],
  },
  {
    matchday: 11,
    date: "2026-11-08",
    matches: [
      ["Cagliari", "Frosinone"],
      ["Fiorentina", "Juventus"],
      ["Genoa", "Milan"],
      ["Inter", "Como"],
      ["Monza", "Atalanta"],
      ["Napoli", "Lazio"],
      ["Parma", "Bologna"],
      ["Roma", "Sassuolo"],
      ["Torino", "Lecce"],
      ["Venezia", "Udinese"],
    ],
  },
  {
    matchday: 12,
    date: "2026-11-22",
    matches: [
      ["Atalanta", "Inter"],
      ["Bologna", "Udinese"],
      ["Como", "Cagliari"],
      ["Juventus", "Venezia"],
      ["Lazio", "Lecce"],
      ["Milan", "Frosinone"],
      ["Monza", "Fiorentina"],
      ["Napoli", "Torino"],
      ["Parma", "Roma"],
      ["Sassuolo", "Genoa"],
    ],
  },
  {
    matchday: 13,
    date: "2026-11-29",
    matches: [
      ["Cagliari", "Milan"],
      ["Como", "Juventus"],
      ["Frosinone", "Parma"],
      ["Inter", "Genoa"],
      ["Lecce", "Atalanta"],
      ["Roma", "Monza"],
      ["Sassuolo", "Napoli"],
      ["Torino", "Lazio"],
      ["Udinese", "Fiorentina"],
      ["Venezia", "Bologna"],
    ],
  },
  {
    matchday: 14,
    date: "2026-12-06",
    matches: [
      ["Bologna", "Roma"],
      ["Fiorentina", "Cagliari"],
      ["Frosinone", "Inter"],
      ["Genoa", "Torino"],
      ["Juventus", "Udinese"],
      ["Lazio", "Atalanta"],
      ["Milan", "Parma"],
      ["Monza", "Como"],
      ["Napoli", "Lecce"],
      ["Venezia", "Sassuolo"],
    ],
  },
  {
    matchday: 15,
    date: "2026-12-13",
    matches: [
      ["Atalanta", "Genoa"],
      ["Cagliari", "Venezia"],
      ["Como", "Bologna"],
      ["Inter", "Torino"],
      ["Juventus", "Monza"],
      ["Lazio", "Roma"],
      ["Lecce", "Sassuolo"],
      ["Napoli", "Milan"],
      ["Parma", "Fiorentina"],
      ["Udinese", "Frosinone"],
    ],
  },
  {
    matchday: 16,
    date: "2026-12-20",
    matches: [
      ["Atalanta", "Napoli"],
      ["Fiorentina", "Bologna"],
      ["Frosinone", "Lazio"],
      ["Genoa", "Udinese"],
      ["Lecce", "Inter"],
      ["Milan", "Como"],
      ["Roma", "Juventus"],
      ["Sassuolo", "Parma"],
      ["Torino", "Cagliari"],
      ["Venezia", "Monza"],
    ],
  },
  {
    matchday: 17,
    date: "2027-01-03",
    matches: [
      ["Bologna", "Juventus"],
      ["Cagliari", "Genoa"],
      ["Como", "Lecce"],
      ["Fiorentina", "Lazio"],
      ["Inter", "Sassuolo"],
      ["Monza", "Milan"],
      ["Parma", "Napoli"],
      ["Roma", "Frosinone"],
      ["Torino", "Venezia"],
      ["Udinese", "Atalanta"],
    ],
  },
  {
    matchday: 18,
    date: "2027-01-06",
    matches: [
      ["Atalanta", "Como"],
      ["Frosinone", "Bologna"],
      ["Genoa", "Monza"],
      ["Juventus", "Torino"],
      ["Lazio", "Inter"],
      ["Lecce", "Parma"],
      ["Milan", "Fiorentina"],
      ["Napoli", "Cagliari"],
      ["Sassuolo", "Udinese"],
      ["Venezia", "Roma"],
    ],
  },
  {
    matchday: 19,
    date: "2027-01-10",
    matches: [
      ["Bologna", "Genoa"],
      ["Cagliari", "Sassuolo"],
      ["Como", "Lazio"],
      ["Fiorentina", "Lecce"],
      ["Inter", "Juventus"],
      ["Monza", "Frosinone"],
      ["Parma", "Venezia"],
      ["Roma", "Milan"],
      ["Torino", "Atalanta"],
      ["Udinese", "Napoli"],
    ],
  },
  {
    matchday: 20,
    date: "2027-01-17",
    matches: [
      ["Atalanta", "Roma"],
      ["Cagliari", "Como"],
      ["Juventus", "Genoa"],
      ["Lazio", "Bologna"],
      ["Lecce", "Udinese"],
      ["Milan", "Torino"],
      ["Napoli", "Fiorentina"],
      ["Parma", "Inter"],
      ["Sassuolo", "Monza"],
      ["Venezia", "Frosinone"],
    ],
  },
  {
    matchday: 21,
    date: "2027-01-24",
    matches: [
      ["Bologna", "Atalanta"],
      ["Como", "Napoli"],
      ["Fiorentina", "Sassuolo"],
      ["Frosinone", "Milan"],
      ["Genoa", "Parma"],
      ["Inter", "Venezia"],
      ["Juventus", "Cagliari"],
      ["Lecce", "Torino"],
      ["Monza", "Lazio"],
      ["Roma", "Udinese"],
    ],
  },
  {
    matchday: 22,
    date: "2027-01-31",
    matches: [
      ["Atalanta", "Fiorentina"],
      ["Cagliari", "Parma"],
      ["Genoa", "Lecce"],
      ["Lazio", "Venezia"],
      ["Milan", "Juventus"],
      ["Monza", "Roma"],
      ["Napoli", "Inter"],
      ["Sassuolo", "Como"],
      ["Torino", "Frosinone"],
      ["Udinese", "Bologna"],
    ],
  },
  {
    matchday: 23,
    date: "2027-02-07",
    matches: [
      ["Atalanta", "Lazio"],
      ["Bologna", "Milan"],
      ["Como", "Monza"],
      ["Fiorentina", "Udinese"],
      ["Inter", "Cagliari"],
      ["Juventus", "Sassuolo"],
      ["Lecce", "Napoli"],
      ["Parma", "Frosinone"],
      ["Roma", "Torino"],
      ["Venezia", "Genoa"],
    ],
  },
  {
    matchday: 24,
    date: "2027-02-14",
    matches: [
      ["Bologna", "Como"],
      ["Cagliari", "Lazio"],
      ["Frosinone", "Fiorentina"],
      ["Genoa", "Atalanta"],
      ["Inter", "Milan"],
      ["Monza", "Lecce"],
      ["Napoli", "Juventus"],
      ["Roma", "Parma"],
      ["Torino", "Sassuolo"],
      ["Udinese", "Venezia"],
    ],
  },
  {
    matchday: 25,
    date: "2027-02-21",
    matches: [
      ["Atalanta", "Monza"],
      ["Como", "Torino"],
      ["Fiorentina", "Inter"],
      ["Juventus", "Bologna"],
      ["Lazio", "Napoli"],
      ["Lecce", "Frosinone"],
      ["Milan", "Genoa"],
      ["Sassuolo", "Roma"],
      ["Udinese", "Parma"],
      ["Venezia", "Cagliari"],
    ],
  },
  {
    matchday: 26,
    date: "2027-02-28",
    matches: [
      ["Bologna", "Lecce"],
      ["Cagliari", "Udinese"],
      ["Como", "Milan"],
      ["Frosinone", "Napoli"],
      ["Genoa", "Lazio"],
      ["Inter", "Atalanta"],
      ["Monza", "Juventus"],
      ["Parma", "Sassuolo"],
      ["Roma", "Venezia"],
      ["Torino", "Fiorentina"],
    ],
  },
  {
    matchday: 27,
    date: "2027-03-07",
    matches: [
      ["Atalanta", "Torino"],
      ["Fiorentina", "Venezia"],
      ["Juventus", "Roma"],
      ["Lazio", "Frosinone"],
      ["Lecce", "Como"],
      ["Milan", "Cagliari"],
      ["Monza", "Genoa"],
      ["Napoli", "Parma"],
      ["Sassuolo", "Bologna"],
      ["Udinese", "Inter"],
    ],
  },
  {
    matchday: 28,
    date: "2027-03-14",
    matches: [
      ["Bologna", "Napoli"],
      ["Cagliari", "Fiorentina"],
      ["Como", "Udinese"],
      ["Frosinone", "Monza"],
      ["Genoa", "Roma"],
      ["Lazio", "Juventus"],
      ["Milan", "Sassuolo"],
      ["Parma", "Lecce"],
      ["Torino", "Inter"],
      ["Venezia", "Atalanta"],
    ],
  },
  {
    matchday: 29,
    date: "2027-03-21",
    matches: [
      ["Atalanta", "Milan"],
      ["Fiorentina", "Genoa"],
      ["Inter", "Frosinone"],
      ["Juventus", "Como"],
      ["Monza", "Bologna"],
      ["Napoli", "Venezia"],
      ["Parma", "Lazio"],
      ["Roma", "Lecce"],
      ["Sassuolo", "Cagliari"],
      ["Udinese", "Torino"],
    ],
  },
  {
    matchday: 30,
    date: "2027-04-04",
    matches: [
      ["Cagliari", "Napoli"],
      ["Como", "Fiorentina"],
      ["Frosinone", "Udinese"],
      ["Genoa", "Inter"],
      ["Lecce", "Lazio"],
      ["Milan", "Monza"],
      ["Roma", "Bologna"],
      ["Sassuolo", "Atalanta"],
      ["Torino", "Juventus"],
      ["Venezia", "Parma"],
    ],
  },
  {
    matchday: 31,
    date: "2027-04-11",
    matches: [
      ["Bologna", "Venezia"],
      ["Cagliari", "Atalanta"],
      ["Fiorentina", "Milan"],
      ["Frosinone", "Genoa"],
      ["Inter", "Roma"],
      ["Juventus", "Lecce"],
      ["Lazio", "Torino"],
      ["Napoli", "Sassuolo"],
      ["Parma", "Como"],
      ["Udinese", "Monza"],
    ],
  },
  {
    matchday: 32,
    date: "2027-04-18",
    matches: [
      ["Atalanta", "Udinese"],
      ["Bologna", "Cagliari"],
      ["Como", "Frosinone"],
      ["Fiorentina", "Parma"],
      ["Milan", "Napoli"],
      ["Monza", "Inter"],
      ["Roma", "Lazio"],
      ["Sassuolo", "Lecce"],
      ["Torino", "Genoa"],
      ["Venezia", "Juventus"],
    ],
  },
  {
    matchday: 33,
    date: "2027-04-25",
    matches: [
      ["Cagliari", "Monza"],
      ["Frosinone", "Roma"],
      ["Genoa", "Sassuolo"],
      ["Inter", "Bologna"],
      ["Juventus", "Fiorentina"],
      ["Lazio", "Como"],
      ["Lecce", "Milan"],
      ["Napoli", "Udinese"],
      ["Parma", "Atalanta"],
      ["Venezia", "Torino"],
    ],
  },
  {
    matchday: 34,
    date: "2027-05-02",
    matches: [
      ["Atalanta", "Juventus"],
      ["Bologna", "Fiorentina"],
      ["Como", "Inter"],
      ["Lecce", "Cagliari"],
      ["Milan", "Lazio"],
      ["Monza", "Venezia"],
      ["Roma", "Napoli"],
      ["Sassuolo", "Frosinone"],
      ["Torino", "Parma"],
      ["Udinese", "Genoa"],
    ],
  },
  {
    matchday: 35,
    date: "2027-05-09",
    matches: [
      ["Fiorentina", "Roma"],
      ["Frosinone", "Atalanta"],
      ["Genoa", "Cagliari"],
      ["Inter", "Lecce"],
      ["Lazio", "Sassuolo"],
      ["Napoli", "Monza"],
      ["Parma", "Milan"],
      ["Torino", "Bologna"],
      ["Udinese", "Juventus"],
      ["Venezia", "Como"],
    ],
  },
  {
    matchday: 36,
    date: "2027-05-16",
    matches: [
      ["Bologna", "Frosinone"],
      ["Cagliari", "Torino"],
      ["Como", "Atalanta"],
      ["Juventus", "Inter"],
      ["Lazio", "Udinese"],
      ["Lecce", "Fiorentina"],
      ["Milan", "Roma"],
      ["Monza", "Parma"],
      ["Napoli", "Genoa"],
      ["Sassuolo", "Venezia"],
    ],
  },
  {
    matchday: 37,
    date: "2027-05-23",
    matches: [
      ["Atalanta", "Lecce"],
      ["Fiorentina", "Monza"],
      ["Frosinone", "Cagliari"],
      ["Genoa", "Bologna"],
      ["Inter", "Lazio"],
      ["Parma", "Juventus"],
      ["Roma", "Como"],
      ["Torino", "Napoli"],
      ["Udinese", "Sassuolo"],
      ["Venezia", "Milan"],
    ],
  },
  {
    matchday: 38,
    date: "2027-05-30",
    matches: [
      ["Bologna", "Parma"],
      ["Cagliari", "Roma"],
      ["Como", "Genoa"],
      ["Juventus", "Frosinone"],
      ["Lazio", "Fiorentina"],
      ["Lecce", "Venezia"],
      ["Milan", "Udinese"],
      ["Monza", "Torino"],
      ["Napoli", "Atalanta"],
      ["Sassuolo", "Inter"],
    ],
  },
];

export const serieA1x2Matchdays = rawCalendar;

export const serieA1x2Matches = rawCalendar.flatMap((round) =>
  round.matches.map(([homeTeam, awayTeam], index) => ({
    id: `g${String(round.matchday).padStart(2, "0")}m${String(index + 1).padStart(2, "0")}`,
    matchday: round.matchday,
    date: round.date,
    homeTeam,
    awayTeam,
    officialResult: null,
  })),
);
